services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MOTD: This is a test server running on Minecraft 1.21.4
      LEVEL: world-%date:yyyy-MM-dd%
      TYPE: FABRIC
      MEMORY: 10G
      VERSION: 1.21.4
      SEED: -363139536
      
      RCON_CMDS_STARTUP:  |-
        op TheN4meless0ne
        pregen start 200

      MODRINTH_PROJECTS: |
        fabric-api
        cloth-config
        lithium
        ferrite-core
        no-chat-reports
        spark
        axiom
        bluemap
        better-stats
        tcdcommons
        chunky
        factions
        essential-commands
    ports:
      - "25565:25565"
      - "8100:8100"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}